#pragma once

#ifndef __LOG_PP_COMPTILE_FILTER_HPP__
#define __LOG_PP_COMPTILE_FILTER_HPP__
#ifndef LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL

#if defined(NDEBUG)

#if defined(LOG_PP_RELEASE_LEVEL_FILTER_ERROR)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 1

#elif defined(LOG_PP_RELEASE_LEVEL_FILTER_WARN)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 2

#elif defined(LOG_PP_RELEASE_LEVEL_FILTER_INFO)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 3

#elif defined(LOG_PP_RELEASE_LEVEL_FILTER_DEBUG)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 4

#elif defined(LOG_PP_RELEASE_LEVEL_FILTER_TRACE)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 5

#elif defined(LOG_PP_LEVEL_FILTER_ERROR)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 1

#elif defined(LOG_PP_LEVEL_FILTER_WARN)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 2

#elif defined(LOG_PP_LEVEL_FILTER_INFO)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 3

#elif defined(LOG_PP_LEVEL_FILTER_DEBUG)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 4

#else
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 5

#endif

#else

#if defined(LOG_PP_LEVEL_FILTER_ERROR)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 1

#elif defined(LOG_PP_LEVEL_FILTER_WARN)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 2

#elif defined(LOG_PP_LEVEL_FILTER_INFO)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 3

#elif defined(LOG_PP_LEVEL_FILTER_DEBUG)
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 4

#else
#define LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL 5

#endif

#endif

#endif  // !LOG_PP_DETAIL_ACTIVE_COMPILE_LEVEL
#endif  // !__LOG_PP_COMPTILE_FILTER_HPP__
